- hosts: $ip
  remote_user: root

  tasks:
    - name: upload iptables config
      copy:
        src: /root/ansible/tencent/iptables_v0.1.0.sh
        dest: /tmp/
        owner: root
        group: root
        mode: 0755

    - name: start iptables config
      command: /tmp/iptables_v0.1.0.sh

    - name: update authorized_keys
      copy: 
        content: |
          ssh-rsa 
          ssh-rsa 
        dest: /root/.ssh/authorized_keys

    - name: update hosts.allow
      copy:
        content: |
          sshd:49.65.114.209
          sshd:117.149.198.115
          sshd:122.228.246.249
        dest: /etc/hosts.allow

    - name: update hosts.deny
      copy:
        content: |
          sshd:ALL
        dest: /etc/hosts.deny

    - name: restart ssh
      systemd:
        name: sshd
        state: restarted
