- hosts: pt-dev
  remote_user: root

  tasks:
    - name: adjust sshd_config port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port 22'
        line: 'Port 22'

    - name: adjust sshd_config authentication
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          RSAAuthentication yes
          PubkeyAuthentication yes
          StrictModes no
        marker: "#PubkeyAuthentication yes"

    - name: adjust passauth
      command: sed -i '/PasswordAuthentication/s/yes/no/' /etc/ssh/sshd_config

    - name: update authorized_keys
      copy: 
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4MEOMO4WKM9SM4k3OkieyXRK2GPXDb9pwE+qcwRP/QCVtqw0jHRKBtD/hD1hR5IGOpU1W7uAG38eetbajLEXY29gmSeMg2E4xyvdd4UFszYGNFimqVBtWGeJfmX9mhFnQuKLE5zvRvGaCG0Pv0Qt3L0n2zD300AGLpdp4NOu+F6dMnfMRawKPu1oKa2jf0eVleBjZV5e/AFfGMTil6+Odg4ez3DLWSGtGVCwRw9t7xpEg9MIZNZ58Z08MJcqUsfWR1b33YXZpi/6I2+Cn5WSJ5wNtNeoU9C+++qUHyWC8DJiBkulIlGOIpNt3sDq+E3iIg2s5g1v3zQSUetnCgs3j zhang@zhangdeMacBook-Pro.local
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj9ygULHjH8gAA/PBbv5zMlpbx+0yovdHESegf/LqTIcKj1i8CQNnV0XFRYcsXj4MdvY+y6v5dbTxn2CDPG1XOMMyzxJ09EP4JC0u5xFFnyETffRyrszF4jhwMQKgZcPlGrNCcxHL3hq+6pJsOCGizf7xmnl8dt0vANWtsYBnhvPixBeA6U3vIYbiSagQSKXSPvmX9AzhtLSXNvN6HK24m48qRxDbJGxasPVTOS+WPfysB/Gtp3AYNileSXcST5gKj9jOpeo22uRBZipz+DWjUt9y2sCyseYRPwXcPnfhAagi98r1fA2WiZCpu/Am1tBqJ3oCveZqqpCnWHehf9eX+FigmMwZr8xCsFEGRngRZAy0A+CUapmgPlQDilBxU/5cMUptFgKA8W+JUv+tZPmcUcTDCgMnbPv+CGbYloL3eNCkEWWKGvD5+4gMrNqX0hc23TV1vbh2FWXBF1d/U1TwMRXvd5XjINlDqEbTTG/FcwlQi9FNZ3J84BQLPhZu56yjaaVnMSaiLCRQDgnvyRq1XhvKOu2trur3qeDgeX+JCgPQDjV2BuFcyoNgBDVfeY++0+LRqJP8xIEM0r52FBLscMF5of2knPaSgu+HykAK8xUt109Z/QQ9rrn6V2cRh6JpYjRxN0iTRubZkerwBhVCtDmBlC5AjoI30BgNaFCIIWQ== zhang@zhangdeMacBook-Pro.local
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDqV+0sP7N+7YQdxuCaR2XIdwXO67Gk1F5Xqc6YB8XEpU6bh5rK9GnGzJ1XzDoDgNP6NXURQ/u+vT22yvH5lY5++5f5pf93nTFwkri8xmiHHuVYDT94/lJgJuU3vPTkLhh4qnWk+VfCplqQxPOZMkVVTaGeP5ufJH/lXl9OmnfTxXpnCa1aGtLW3ye8JFnAAHPus/wfHL07dW3+TUYdHIiUYAaV8LlUB68/Eh7WUP0jglVaA3v1liasylPrUYRMRcAF+OcbOYdSeOfp8Aft44hSp/c3TL0pf7J+ssmKZ4j0Ok/AKpnTNErTtlBY311bzVRwZ4R74kAIseqrkMF/zU+p root@ubuntu-linux-22-04-desktop
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdYQEbOQrnXG5MFxBhpXrYOZrZnMSwnlZrHSVj/0PS6hpXv0UjFGg2QPuN6nof1Sb3To/IyEUBJwKXL1Ysd3Fz/abAN9jZBdl6Nv6RpqQerpjvNArfn7BK0KWCpbhwxWUv/oWaxKaBPKlpQgYKnoed3NHn3dKba/6Izo8RR1TMoBoX7eboAYB5zHmfeN9DSZpa2QQE3ZcrrrqAyS8/+0soOVeE1Z0jgsREZxo6munST3p6XUV4opqOgRvbRJFMuFOITtXewckyZXeE2aA6Xc1l+qp7xmdLnFydtQ5xm0CPALigfKuAYtr2of5p3crz9/B2EVsgiDA/4om4kMAZ58Nr root@master
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEc2/xXEUORX22I/EHtxjQdE6STAIvL+wSKPoshyGXnZcEQQzSQWZZpRjT2htKXhKTI96F0TfF7FDU0rge8PmQ7yQsECOD2vVuMa57uWTUwKUXZxdeyz+zYU8HXDM8vwMfBPrHQq5AcLpwdvQ4kZkEouGUQD7yKLyor7RKEtPSBgAKpdAXnYXq31LD/C0oThFOZOhu+A/bwGev2tlBgFVdz4N5s92lAzHHqOdzMhVOtSeA+ZMoaqbwJqUUTY+gIt3aaIu6TjxtWgim8NfTMeZXwhDiECFgoL073tQZGFtBVFiS5NOj7c8y2BotJoGVwLyOy+F2i8qN0YtTi/HGJvD/ xg@xgdeMacBook-Pro.local
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCndl1v5gpXYgGYLiT3PRtIWmQtBFAX2MPlPtbu8646n++xOicKLEpChgKEYWtV13OYDLhadmPHFQ2DWXRdhfPyVgWpaQhXHJHP4vBIoqvSD5wDRk7i6gY1lfiwxwOddwrKXGfxsCjt+Cow+hUCUF7BEvMXNYkqEga62yJ2hkQkO5HnIbKXC/WbXJen9X0GdJ9FjwL6SGxWf3mDkd7Dx564BD1tJzFnwidUTgUZQdYOTvy4IqRVBXgiRHTnL5I4b9dl9+H1VNxySB7fTd2esdnyIn7V6qWcBPRPJcAK0m/wkx0r3cftc0BkVX0ovs+CCNQK1rpctL4Wl+f1MEV/4pmD luo
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeFYI7Bkx57n6F1VQtyEl5WWz3XZJL5CZg5c0fp+TjiF61OzzW96F5d9JGGvMAk4JlLIsAF3MNKyKFeZRfTtXUkp67DwsAVzUiNAe3pC2JA7mtZ3QM0YGkTFOSNue25X61/ZqcIaaR748ieahCA7TQsQYA/ONl2Bt5BXJcz2ZaeFKoPjfC2nMRRNGfnVBP/kjdsCcZ5+dUJ6HH0ey/duyo+odA4s5rXxILXfdRrKGBONDha92+9mrSN53sfhfQ129QmxRhIiBOXcmL7GByoont9qUgvXRcA58NIQvu6dbLMHC25CtMWSuiLaj8iMt548jmFBvDURQLLF00jiiWYgM1zR4LD3cYHGj9KqXeycfl8/btI6JlQeY65ppCx69dYHEgemVXWBYBIrMhe3enMF+gqG/lrJdZcqkYr1XLPW8tH1kbiEf9PwxhHqqVo6FCYBiTfiRI6BTSFUfE3k/jKEZF5H7Ku2qr9LAuG3Lj3aj5k326oy4wH7jwYcj3FCwCbmM= fanyiwen02@gmail.com

        dest: /root/.ssh/authorized_keys

    - name: restart ssh
      systemd:
        name: sshd
        state: restarted